services:
  restaurant-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-web-app
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge
